export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_CAST = 'FETCH_MOVIE_CAST';

export const FETCH_MOVIE_INDONESIA = 'FETCH_MOVIE_INDONESIA';
export const FETCH_MOVIE_RECOMMENDATIONS = 'FETCH_MOVIE_RECOMMENDATIONS';
export const FETCH_MOVIE_ALIKE = 'FETCH_MOVIE_ALIKE';

export const FETCH_MOVIE_SEARCH = 'FETCH_MOVIE_SEARCH';

export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const REQUEST_ACCOUNT_CREDIT = 'REQUEST_ACCOUNT_CREDIT';
export const DISPATCH_ACCOUNT_CREDIT = 'DISPATCH_ACCOUNT_CREDIT';
