export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_CAST = 'FETCH_MOVIE_CAST';

export const FETCH_MOVIE_INDONESIA = 'FETCH_MOVIE_INDONESIA';
export const FETCH_MOVIE_RECOMMENDATIONS = 'FETCH_MOVIE_RECOMMENDATIONS';
export const FETCH_MOVIE_ALIKE = 'FETCH_MOVIE_ALIKE';

export const FETCH_MOVIE_SEARCH = 'FETCH_MOVIE_SEARCH';
